services:

    _defaults:
        autowire: true
        autoconfigure: true
        
    OSW3\Utils\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    # gedmo.listener.sluggable:
    #     class: Gedmo\Sluggable\SluggableListener
    #     tags:
    #         - { name: doctrine.event_subscriber, connection: default }
